### ISSUE TITLE
Extension not working - error in console

### ISSUE THREAD

**Issue by davemacrae** [andyvalerio/photoprism-geolocation#4] opened 2023-03-10 10:16 UTC
Hi,

I've been trying to get your extension working on my current setup with no success.

I finally noticed in the Dev console the following error:

```
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at contentScript.js:47:10
```

Extension version 1.3 (loaded locally after git clone/loaded from Chrome store)
Chrome Version: 110.0.5481.180 (Official Build) (64-bit)
Photoprism Version: Build [221118-e58fee0fb]

Any ideas?

Thanks

Dave

**Comment by andyvalerio** [comment] 2023-03-10 10:28
Hi!
Let me test with the latest version of Photoprism this weekend and I'll get back to you.
Thanks!

**Comment by andyvalerio** [comment] 2023-03-11 09:33
Hi @davemacrae, 
looks like I got stuck on an old version of Photoprism and I didn't even notice! 😅 Now I'm on the latest and I get the same error as you. 
Let me look into it later today and hopefully there is an easy solution. 
/Andy

**Comment by andyvalerio** [comment] 2023-03-11 09:48
I committed a small change and it seems to be working again for me now. Could you give it a try? 
Restart the browser after you install the new version. 

Thanks a lot for the help, I would never notice if it wasn't for you.

**Comment by davemacrae** [comment] 2023-03-11 11:29
Hi Andy,

Unfortunately, not working for me although there are no errors appearing in the console now.

Just to make sure I have the steps right.

Load extension from local git repository.
Restart browser (I even rebooted just to make sure)
Logged onto my Photoprism site,.
Search for a photo
Click to display
Select Edit icon (pen)

I then just get the normal edit dialogue.

Is that the correct sequence?

**Comment by andyvalerio** [comment] 2023-03-11 14:30
It's the correct sequence. Can you pull the latest changes and try one more time? I think I figured it out. 🙈

**Comment by davemacrae** [comment] 2023-03-11 17:14
That's working now.

Many thanks for your efforts.

Dave

**Comment by andyvalerio** [comment] 2023-03-11 23:18
Nice, good to read that. The problem is that the latest version of Photoprism takes a bit longer to complete loading the pages so some of the elements in the document are not present when the extension loads. 
The proper solution is to wait for these elements (for example the div with id "app") to be available before executing the extension's code, but I don't really have time to implement that right now. 
As a temporary solution I simply added a 1 sec delay, 🤣 that should be OK for a while.

**Closed as completed by andyvalerio** 2023-03-11 23:18 UTC
